name: CI/CD

on:
  pull_request:
    branches: [$default-branch]

jobs:
  tests:
    name: Execute Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Test
        run: ./test.sh
