name: CI/CD
on: push
jobs:
  build:
    name: Execute Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Test
        run: ./test.sh
